import type { Metadata } from "next";
import { Bayon, Edu_NSW_ACT_Foundation } from "next/font/google";
import { Navbar } from "@/components/navbar";
import "./globals.css";

const bayon = Bayon({
  weight: ["400"],
  subsets: ["latin"],
});

const sketch = Edu_NSW_ACT_Foundation({
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "feathers",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialised tracking-wide flex flex-col h-[100dvh] bg-green-1">
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
